In [1]:
import numpy as np

# 1. Instagram post likes
likes = np.array([120, 250, 180, 450, 320, 510, 275])

print("Instagram Likes:", likes)
print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)


Instagram Likes: [120 250 180 450 320 510 275]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [2]:
# 2. Daily step counts for 5 days
steps_2d = np.array([
    [3500, 6200],
    [4200, 7100],
    [3000, 6800],
    [5100, 7500],
    [3900, 6500]
])

print("\nOriginal 2D array:")
print(steps_2d)
print("Shape:", steps_2d.shape)

# Convert 2D array into 1D array
steps_1d = steps_2d.reshape(10)
print("\nAfter converting to 1D:")
print(steps_1d)
print("Shape:", steps_1d.shape)

# Convert back to 2D with 5 rows and 2 columns
steps_back = steps_1d.reshape(5, 2)
print("\nAfter converting back to 2D:")
print(steps_back)
print("Shape:", steps_back.shape)



Original 2D array:
[[3500 6200]
 [4200 7100]
 [3000 6800]
 [5100 7500]
 [3900 6500]]
Shape: (5, 2)

After converting to 1D:
[3500 6200 4200 7100 3000 6800 5100 7500 3900 6500]
Shape: (10,)

After converting back to 2D:
[[3500 6200]
 [4200 7100]
 [3000 6800]
 [5100 7500]
 [3900 6500]]
Shape: (5, 2)


In [3]:

# 3. Zomato food item prices
prices = np.array([
    120, 250, 180, 99,
    150, 220, 175, 300,
    130, 199, 275, 160
])

print("\nOriginal food prices:")
print(prices)
print("Shape:", prices.shape)

# Convert into a 3x4 array
prices_2d = prices.reshape(3, 4)
print("\n3x4 prices array:")
print(prices_2d)

# ravel() returns a flattened view whenever possible.
# Changes to the ravel result may affect the original array.
prices_ravel = prices_2d.ravel()
print("\nUsing ravel():")
print(prices_ravel)

# flatten() always creates a COPY of the array.
# Changes to the flatten result do not affect the original array.
prices_flatten = prices_2d.flatten()
print("\nUsing flatten():")
print(prices_flatten)

# resize() changes the shape of the array itself
prices_resize = prices_2d.copy()
prices_resize.resize(4, 3)
print("\nUsing resize() - 4x3:")
print(prices_resize)


Original food prices:
[120 250 180  99 150 220 175 300 130 199 275 160]
Shape: (12,)

3x4 prices array:
[[120 250 180  99]
 [150 220 175 300]
 [130 199 275 160]]

Using ravel():
[120 250 180  99 150 220 175 300 130 199 275 160]

Using flatten():
[120 250 180  99 150 220 175 300 130 199 275 160]

Using resize() - 4x3:
[[120 250 180]
 [ 99 150 220]
 [175 300 130]
 [199 275 160]]


In [4]:
# 4. Spotify playlist grid
playlist = np.array([
    [10, 5, 8],   # Playlist 1
    [7, 12, 6],   # Playlist 2
    [15, 4, 9]    # Playlist 3
])

print("\nOriginal Spotify playlist grid:")
print(playlist)

# Transpose using T
transposed_T = playlist.T
print("\nTranspose using T:")
print(transposed_T)

# Transpose using np.transpose()
transposed_function = np.transpose(playlist)
print("\nTranspose using np.transpose():")
print(transposed_function)


Original Spotify playlist grid:
[[10  5  8]
 [ 7 12  6]
 [15  4  9]]

Transpose using T:
[[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]

Transpose using np.transpose():
[[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]


In [5]:

# 5. Flipkart product ratings
ratings = np.array([
    4, 5, 3, 4, 2,
    5, 4, 5, 3, 4,
    2, 5, 4, 3, 5
])

print("\nOriginal 1D ratings:")
print(ratings)
print("Shape:", ratings.shape)

# Convert 1D array into a 3x5 array
ratings_3x5 = ratings.reshape(3, 5)
print("\nRatings as 3x5 array:")
print(ratings_3x5)

# Convert back to 1D using flatten()
ratings_flattened = ratings_3x5.flatten()
print("\nAfter flatten():")
print(ratings_flattened)


Original 1D ratings:
[4 5 3 4 2 5 4 5 3 4 2 5 4 3 5]
Shape: (15,)

Ratings as 3x5 array:
[[4 5 3 4 2]
 [5 4 5 3 4]
 [2 5 4 3 5]]

After flatten():
[4 5 3 4 2 5 4 5 3 4 2 5 4 3 5]
